name: Deploy to Test WordPress Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to FTP server (test WP site)
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: sftp://opal15.opalstack.com
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./respectify/
        server-dir: /home/vintagedave/apps/respectify-test/wp-content/plugins/respectify
