name: Deploy to Test WordPress Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change to repository directory
      run: cd ${{ github.workspace }} && cd respectify && echo "Respecitfy directory:" && pwd && ls -la

    - name: Deploy to SFTP server
      run: |
        echo "Current directory:"
        pwd
        echo "Contents of the current directory:"
        ls -la
        rsync -avz --progress -e "ssh -p ${{ secrets.SFTP_PORT }}" ./respectify/ ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:/home/vintagedave/apps/respectify-test/wp-content/plugins/respectify/
      env:
        RSYNC_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        
